import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { generateCsv } from "../utils/generateCsv";
import { UsersTypes } from "../types/User";

const Home: NextPage = () => {
  const [users, setUsers] = useState<UsersTypes[]>();

  useEffect(() => {
    fetch("https://jsonplaceholder.typicode.com/users/")
      .then((res) => res.json())
      .then((data) => setUsers(data));
  }, []);

  const downloadCsv = () => {
    const headers = {
      name: "Name",
      username: "Username",
      email: "Email",
      phone: "Phone",
      website: "Website",
    };

    const itemsFormatted: UsersTypes[] = [];

    // format the data
    users?.forEach((user: any) => {
      itemsFormatted.push({
        name: user.name,
        username: user.username,
        email: user.email,
        phone: user.phone,
        website: user.website,
      });
    });

    const fileTitle = "users";

    generateCsv(headers, itemsFormatted, fileTitle);
  };

  return (
    <div
      style={{
        display: "flex",
        height: "100vh",
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <Head>
        <title>JSON to CSV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2 style={{ marginBottom: "20px" }}>Json to CSV</h2>
        <p
          style={{ textAlign: "center", cursor: "pointer" }}
          onClick={downloadCsv}
        >
          Download CSV
        </p>
      </main>
    </div>
  );
};

export default Home;
